name: AllayMcLandClaimRemastered
main: com.allaymc.landclaimremastered.AllayClaimsPlugin
version: ${version}
api-version: "1.21"
softdepend:
  - GriefPrevention
  - PlaceholderAPI
  - TAB
  - LuckPerms

commands:
  claim:
    description: Open the claim menu
    usage: /claim
    permission: allayclaim.use
  claimadmin:
    description: Open the admin menu
    usage: /claimadmin
    permission: allayclaim.admin

permissions:
  allayclaim.use:
    default: true
  allayclaim.admin:
    default: op
  allayclaim.reload:
    default: op
