name: AllayMcLandClaimRemastered
main: com.allaymc.landclaimremastered.AllayClaimsPlugin
version: ${version}
api-version: '1.21'
softdepend:
  - GriefPrevention
  - PlaceholderAPI
  - TAB
  - LuckPerms
commands:
  claim:
    description: Open the main claim menu
    usage: /claim
    permission: allayclaim.use
  claimreload:
    description: Reload the plugin
    usage: /claimreload
    permission: allayclaim.reload
  claimadmin:
    description: Claim admin tools
    usage: /claimadmin
    permission: allayclaim.admin
permissions:
  allayclaim.use:
    default: true
  allayclaim.reload:
    default: op
  allayclaim.admin:
    default: op
